# Placeholder
# type DateTime {

type Product {
  id            : ID!
  name          : String!
  description   : String!

  featuredImage : Image          @relation(name: "FEATURES"     , direction: IN)
  images        : [Image]!       @relation(name: "IMAGES"       , direction: IN)

  type          : ProductType!   @relation(name: "TYPE"         , direction: IN)
  status        : ProductStatus! @relation(name: "STATUS"       , direction: IN)
  tags          : [Tag]!         @relation(name: "TAGGED"       , direction: IN)
  inventory     : Int!

  publishedBy   : User           @relation(name: "PUBLISHED"    , direction: IN)
  publishedAt   : DateTime

  createdAt     : DateTime
  updatedAt     : DateTime
  deletedAt     : DateTime
}

type User {
  id            : ID!
  name          : String!

  products      : [Product]      @relation(name: "PUBLISHED"    , direction: OUT)
  images        : [Image]!       @relation(name: "UPLOADED"     , direction: OUT)

  createdAt     : DateTime
  updatedAt     : DateTime
  deletedAt     : DateTime
}

type ProductType {
  id            : ID!
  name          : String!
  description   : String!

  products      : [Product]!     @relation(name: "TYPE"         , direction: OUT)

  createdAt     : DateTime!
  updatedAt     : DateTime!
  deletedAt     : DateTime
}

type ProductStatus {
  id            : ID!
  name          : String!
  description   : String!

  products      : [Product]!     @relation(name: "STATUS"       , direction: OUT)

  createdAt     : DateTime!
  updatedAt     : DateTime!
  deletedAt     : DateTime
}

type Tag {
  id            : ID!
  name          : String!
  description   : String!

  tags          : [Product]!     @relation(name: "TAGGED"       , direction: IN)

  createdAt     : DateTime!
  updatedAt     : DateTime!
  deletedAt     : DateTime
}

type Image {
  id            : ID!
  name          : String!
  description   : String!

  products      : [Product]!     @relation(name: "IMAGES"   , direction: OUT)
  features      : [Product]!     @relation(name: "FEATURES" , direction: OUT)

  createdAt     : DateTime!
  updatedAt     : DateTime!
  deletedAt     : DateTime
}
