version: '3'
services:
  neo4j:
    image: neo4j:4.3.4-community
    user: "${UID}:${GID}"
    hostname: neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data/data:/data
      - ./data/logs:/logs
      - ./data/import:/var/lib/neo4j/import
      - ./data/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_logs_debug_level=DEBUG
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=["apoc"]
